name: Check Formatting

on: [pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: serverless
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run check-formatting