name: serverless check formatting

on: [pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: serverless
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd serverless
    - run: npm install
    - run: npm run check-formatting