name: Lint Cloudformation Template

on: [pull_request]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: "./serverless/template.yml"