name: Lint Cloudformation Template

on: push

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run cfn-lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: "./serverless/template.yml"
